# permissions for end users to view examples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-viewer-role
rules:
- apiGroups:
  - ipam.onmetal.de
  resources:
  - examples
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.onmetal.de
  resources:
  - examples/status
  verbs:
  - get
