apiVersion: ipam.metal.ironcore.dev/v1alpha1
kind: IP
metadata:
  name: ipv6-resource-ip-sample
spec:
  subnetName: ipv6-child-cidr-subnet-sample
  resourceReference:
    apiVersion: ipam.metal.ironcore.dev/v1alpha1
    kind: NetworkCounter
    name: referred-networkcounter-sample
