apiVersion: ipam.onmetal.de/v1alpha1
kind: IP
metadata:
  name: ipv6-resource-and-ip-ip-sample
spec:
  subnetName: ipv6-child-cidr-subnet-sample
  resourceReference:
    apiVersion: ipam.onmetal.de/v1alpha1
    kind: NetworkCounter
    name: referred-networkcounter-sample
  ip: fd34:5d8f:e75e:f3a2::0002
