apiVersion: ipam.metal.ironcore.dev/v1alpha1
kind: Subnet
metadata:
  name: ipv6-child-capacity-subnet-sample
spec:
  capacity: "8589934592"
  parentSubnetName: "ipv6-parent-cidr-subnet-sample"
  networkName: network-sample
  regions:
    - name: euw
      availabilityZones:
        - a
        - b
